version: '2.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=packages
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  flaskmigration:
    image: quiltdata/flask
    environment:
      - AWS_ACCESS_KEY_ID=ddccbbaa
      - AWS_SECRET_ACCESS_KEY=abcd
      - QUILT_DEFAULT_SENDER=support@quiltdata.io
      - QUILT_SECRET_KEY=testing
      - QUILT_SERVER_CONFIG=docker_config.py
      - REGISTRY_URL=http://localhost:5000
      - STRIPE_SECRET_KEY=
    depends_on:
      db:
        condition: service_healthy
    command:
      flask db upgrade

  flask:
    image: quiltdata/flask
    environment:
      - AWS_ACCESS_KEY_ID=ddccbbaa
      - AWS_SECRET_ACCESS_KEY=abcd
      - DEPLOYMENT_ID=dev
      - MAIL_DEV=1
      - REGISTRY_URL=http://localhost:5000
      - STRIPE_SECRET_KEY=
      - QUILT_DEFAULT_SENDER=support@quiltdata.io
      - QUILT_SECRET_KEY=testing
      - QUILT_SERVER_CONFIG=docker_config.py
    depends_on:
      db:
        condition: service_healthy

  nginxflask:
    image: nginx:latest
    ports:
      - "5000:80"
    depends_on:
      - flask
    volumes:
      - ./nginx/nginx-quilt.conf:/etc/nginx/nginx-quilt.template
    environment:
      - UWSGI_HOST=flask
      - UWSGI_PORT=9000
      - NGINX_PORT=80
    command: /bin/bash -c "envsubst < /etc/nginx/nginx-quilt.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  s3:
    image: quiltdata/nginx-s3-proxy
    ports:
      - "5001:5001"
