version: '2.1'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=packages
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 3s
      retries: 3
    ports:
      - "5432:5432"

  flaskmigration:
    build: .
    image: quiltdata/flask
    environment:
      - AWS_ACCESS_KEY_ID=ddccbbaa
      - AWS_SECRET_ACCESS_KEY=abcd
      - QUILT_SERVER_CONFIG=docker_config.py
      - STRIPE_SECRET_KEY=STRIPETEST
      - REGISTRY_HOST=http://localhost:5000
      - QUILT_DEFAULT_SENDER=support@quiltdata.io
      - MAIL_DEV=1
      - QUILT_SECRET_KEY=testing
    depends_on:
      db:
        condition: service_healthy
    command:
      flask db upgrade

  s3:
    build: nginx-s3
    image: quiltdata/nginx-s3-proxy
    ports:
      - "5001:5001"

  catalog:
    build: ../catalog
    image: quiltdata/catalog
    environment:
      - REGISTRY_URL=http://localhost:5000
      - USER_API=http://localhost:5000/api-root
      - SIGN_OUT_URL=http://localhost:5000/logout
      - STRIPE_KEY=NOSTRIPE
    ports:
      - "3000:80"
