[project]
name = "t4_lambda_thumbnail"
version = "0.0.1"
requires-python = ">=3.9"

dependencies = [
  "aicsimageio>=3,<3.1",
  "imageio>=2.10.0,<=2.31.2",  # newer versions fail because of missing tifffile.TiffPage in tifffile==0.15.1
  "numpy>=1.21.5,<2",
  "pdf2image>=1.13.1,<2",
  "Pillow>=9.0.1,<11",
  "python-pptx>=0.6.21,<0.7",
  "requests>=2.26.0,<3",
  "t4_lambda_shared[lambda] @ https://github.com/quiltdata/quilt/archive/f45d8ab51f2d60e98efda7510322f94d822e4eb4.zip#subdirectory=lambdas/shared",
]
