[tool.poetry]
name = "testdocs"
version = "0.1.0"
description = ""
authors = ["Ernest Prabhakar <ernest@quiltdata.io>"]

[tool.poetry.dependencies]
python = "^3.11"
pytest_codeblocks = "^0.16.1"
altair = "^4.2.0"
pandas = "^2"
quilt3 = "^6"

[tool.poetry.dev-dependencies]
pytest = "^7.1.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
